"""
Recommendation model - THE MOST IMPORTANT TABLE IN THE SYSTEM.

Generated by the recommendation engine based on rules:
- Idle EC2 (CPU < 5% for 7+ days)
- Unattached EBS volumes
- Oversized / underutilized RDS
- Storage optimization opportunities
"""

import uuid
import enum
from datetime import datetime, timezone

from sqlalchemy import String, Numeric, Text, DateTime, ForeignKey, Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base
from app.db.types import GUID


class RecommendationType(str, enum.Enum):
    DELETE_RESOURCE = "DELETE_RESOURCE"
    RESIZE_INSTANCE = "RESIZE_INSTANCE"
    OPTIMIZE_STORAGE = "OPTIMIZE_STORAGE"
    CHANGE_STORAGE_CLASS = "CHANGE_STORAGE_CLASS"
    RIGHTSIZE_RDS = "RIGHTSIZE_RDS"


class RiskLevel(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class Priority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RecommendationStatus(str, enum.Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    DISMISSED = "DISMISSED"
    IMPLEMENTED = "IMPLEMENTED"


class Recommendation(Base):
    __tablename__ = "recommendations"

    id: Mapped[uuid.UUID] = mapped_column(
        GUID(), primary_key=True, default=uuid.uuid4
    )
    resource_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("resource_inventory.id"), nullable=False
    )

    recommendation_type: Mapped[RecommendationType] = mapped_column(
        SQLEnum(RecommendationType, name="recommendation_type_enum"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    estimated_monthly_savings: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False, default=0)
    confidence_score: Mapped[float] = mapped_column(Numeric(5, 2), nullable=False, default=0)

    risk_level: Mapped[RiskLevel] = mapped_column(
        SQLEnum(RiskLevel, name="risk_level_enum"), nullable=False, default=RiskLevel.LOW
    )
    priority: Mapped[Priority] = mapped_column(
        SQLEnum(Priority, name="priority_enum"), nullable=False, index=True
    )
    status: Mapped[RecommendationStatus] = mapped_column(
        SQLEnum(RecommendationStatus, name="recommendation_status_enum"),
        nullable=False,
        default=RecommendationStatus.OPEN,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
