"""Add is_localstack to cloud_account

Revision ID: 38f627f3741a
Revises: 9ece81570744
Create Date: 2026-06-14 23:47:43.791245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f627f3741a'
down_revision: Union[str, Sequence[str], None] = '9ece81570744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_accounts', sa.Column('is_localstack', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_accounts', 'is_localstack')
    # ### end Alembic commands ###
