"""full schema with aws credentials

Revision ID: 9ece81570744
Revises: 
Create Date: 2026-06-12 23:56:55.721895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '9ece81570744'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organizations',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('owner_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('cloud_accounts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('organization_id', app.db.types.GUID(), nullable=False),
    sa.Column('provider', sa.Enum('AWS', 'GCP', 'AZURE', name='cloud_provider_enum'), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('role_arn', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('aws_access_key_enc', sa.String(), nullable=True),
    sa.Column('aws_secret_key_enc', sa.String(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'SYNCING', name='cloud_account_status_enum'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copilot_conversations',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('organization_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_health_scores',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('cloud_account_id', app.db.types.GUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('resource_efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cost_efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('storage_efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('forecast_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_health_scores_calculated_at'), 'cloud_health_scores', ['calculated_at'], unique=False)
    op.create_table('copilot_messages',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('conversation_id', app.db.types.GUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['copilot_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_created_at'), 'copilot_messages', ['created_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('cloud_account_id', app.db.types.GUID(), nullable=False),
    sa.Column('forecast_type', sa.Enum('SEVEN_DAY', 'THIRTY_DAY', 'NINETY_DAY', name='forecast_type_enum'), nullable=False),
    sa.Column('current_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('predicted_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence_interval_low', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence_interval_high', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_generated_at'), 'forecasts', ['generated_at'], unique=False)
    op.create_table('resource_inventory',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('cloud_account_id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.Enum('EC2', 'EBS', 'RDS', 'S3', name='resource_type_enum'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('arn', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'STOPPED', 'AVAILABLE', 'IN_USE', 'TERMINATED', 'UNKNOWN', name='resource_status_enum'), nullable=False),
    sa.Column('tags', app.db.types.JSONB_COMPAT(), nullable=True),
    sa.Column('metadata_json', app.db.types.JSONB_COMPAT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_inventory_region'), 'resource_inventory', ['region'], unique=False)
    op.create_index(op.f('ix_resource_inventory_resource_id'), 'resource_inventory', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_inventory_resource_type'), 'resource_inventory', ['resource_type'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='anomaly_severity_enum'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('DELETE_RESOURCE', 'RESIZE_INSTANCE', 'OPTIMIZE_STORAGE', 'CHANGE_STORAGE_CLASS', 'RIGHTSIZE_RDS', name='recommendation_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_monthly_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'DISMISSED', 'IMPLEMENTED', name='recommendation_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_table('resource_costs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('monthly_estimate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('service_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_costs_date'), 'resource_costs', ['date'], unique=False)
    op.create_table('resource_metrics',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(), nullable=False),
    sa.Column('metric_unit', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_metrics_timestamp'), 'resource_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_metrics_timestamp'), table_name='resource_metrics')
    op.drop_table('resource_metrics')
    op.drop_index(op.f('ix_resource_costs_date'), table_name='resource_costs')
    op.drop_table('resource_costs')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_resource_inventory_resource_type'), table_name='resource_inventory')
    op.drop_index(op.f('ix_resource_inventory_resource_id'), table_name='resource_inventory')
    op.drop_index(op.f('ix_resource_inventory_region'), table_name='resource_inventory')
    op.drop_table('resource_inventory')
    op.drop_index(op.f('ix_forecasts_generated_at'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_copilot_messages_created_at'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index(op.f('ix_cloud_health_scores_calculated_at'), table_name='cloud_health_scores')
    op.drop_table('cloud_health_scores')
    op.drop_table('copilot_conversations')
    op.drop_table('cloud_accounts')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
